export const QUOTES = [
  "Discipline is choosing between what you want now and what you want most.",
  "Small daily improvements are the key to staggering long-term results.",
  "You don't have to be extreme, just consistent.",
  "The pain of discipline weighs ounces; the pain of regret weighs tons.",
  "Every hour you put in today is an hour your future self doesn't have to fight for.",
  "Progress, not perfection. Show up today, even if it's not your best day.",
  "Consistency rewards you far more than raw talent ever will.",
  "You're not behind. You're exactly where your effort has placed you — keep adding to it.",
  "One focused hour beats three distracted ones. Protect your blocks.",
  "The version of you that achieves this goal is built in ordinary days like this one.",
  "Nobody sees the early mornings. That's exactly why they matter.",
  "Streaks are built one unremarkable, ordinary day at a time.","Your future is created by what you do today, not tomorrow.",
"Focus is a superpower in a world full of distractions.",
"Success is usually the result of boring consistency.",
"The days you feel least motivated are the days that matter most.",
"Do the work, especially when you don’t feel like it.",
"A goal without daily action is only a wish.",
"Every chapter you study is a brick in the life you’re building.",
"Your habits decide your future more than your intentions do.",
"The compound effect begins with today’s smallest effort.",
"Keep going. Momentum is built, not found.",
"Distraction steals the life you’re trying to create.",
"Choose the desk over the excuse.",
"The gap between average and exceptional is often consistency.",
"One page at a time. One problem at a time. One day at a time.",
"You become what you repeatedly do.",
"Your dream deserves your discipline.",
"Temporary comfort creates permanent disappointment.",
"The strongest motivation comes from keeping promises to yourself.",
"Study because your future opportunities are being decided today.",
"What feels hard now will one day feel like your strength.",
"Every distraction you resist is a vote for your future.",
"You don’t need more time; you need more intention.",
"Master the morning, and the day becomes easier to win.",
"Your competition is your old self, not someone else.",
"The result you want is hidden inside the work you avoid.",
"Dreams demand proof, and effort is the proof.",
"Keep showing up. Your breakthrough may be closer than it looks.",
"The person who studies today has options tomorrow.",
"A focused mind creates a powerful life.",
"Don’t count the hours; make the hours count.",
"Success is rented, and the rent is due every day.",
"The discipline you build now will protect you later.",
"Small sacrifices today create big freedoms tomorrow.",
"Every completed task builds confidence for the next one.",
"Your future self is watching the choices you make today.",
"The harder you work in silence, the louder your results will speak.",
"You are one decision away from a more productive day.",
"Great results are built on ordinary routines.",
"The habit of starting is more important than the fear of failing.",
"Stay focused long enough for your effort to become visible.",
"The best students are not always the smartest; they are often the most consistent.",
"Protect your attention like it is your greatest asset.",
"A disciplined schedule beats random motivation.",
"Keep your head down and let your progress make the noise.",
"One disciplined week can change your confidence.",
"Excuses are expensive; effort is an investment.",
"Every day you study, you make quitting a little less likely.",
"Focus on earning skills, and success will eventually notice you.",
"The life you want is hidden in the work you keep postponing.",
"Be patient with the results, but impatient with the effort.",
"The best way to predict your future is to build it.",
"Your goals require a stronger routine, not a stronger mood.",
"Finish what you started. That is how confidence grows.",
"You will never regret the hours spent improving yourself.",
"The first hour of focused study is the hardest; protect it.",
"Consistency turns difficult things into familiar things.",
"Your notebook is a record of your future success.",
"Stop waiting to feel ready. Begin anyway.",
"Every expert was once someone who kept practicing.",
"Discipline is remembering what you promised yourself.",
"You can’t control the outcome, but you can control today’s effort.",
"A calm, focused mind wins more battles than a frantic one.",
"Progress hides inside repetition.",
"Your degree, career, and future begin with today’s study session.",
"The cost of procrastination is the life you could have built.",
"Work until your goals become your reality.",
"The most successful people often master the basics relentlessly.",
"Every distraction delayed is a goal brought closer.",
"You don’t rise to the level of your goals; you rise to the level of your systems.",
"A focused afternoon can change an entire week.",
"Keep your promises to yourself, especially the small ones.",
"Your future income often follows your present discipline.",
"The next 30 days will pass anyway. Use them well.",
"Study with purpose, not pressure.",
"Your effort is never wasted; it is being invested.",
"The difference between wishing and achieving is action.",
"Protect your routine when your motivation disappears.",
"Success grows quietly before it becomes visible.",
"Every focused session is a deposit into your future.",
"You are closer than you were yesterday. Keep going.",
"The person who can focus has a lifelong advantage.",
"Don’t break the chain of effort.",
"Make discipline your default, not your emergency plan.",
"Your goals are waiting on the other side of consistency.",
"The work you do today will introduce you to a different future.",
"One more chapter. One more practice set. One more step.",
"Keep building even when nobody applauds.",
"The strongest foundation is built when progress feels slow.",
"Action creates clarity; overthinking creates delay.",
"Every day is another chance to become more capable.",
"A single productive day can restart a lost week.",
"You owe your dreams a real attempt.",
"The reward for discipline is becoming someone you respect.",
"Study until confidence replaces fear.",
"Keep choosing the long-term life over the short-term comfort.",
"The path becomes easier when the habit becomes stronger.",
"Your consistency is writing a story your future self will thank you for.",
"Success belongs to those who can keep going without constant encouragement.",
"Today’s effort is tomorrow’s confidence.",
"Stay focused. Stay patient. Stay consistent. The results will come.",
]

export function quoteForDate(dateStr: string) {
  let hash = 0
  for (let i = 0; i < dateStr.length; i++) {
    hash = (hash * 31 + dateStr.charCodeAt(i)) % 1000000
  }
  return QUOTES[hash % QUOTES.length]
}